# FROM node:24-alpine

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# COPY . .

# EXPOSE 5173


# CMD ["npm", "run", "dev"]

FROM node:24-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm install

# --- Stage 2: Development (Make Dev) ---
FROM base AS development

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]



FROM base AS builder

COPY . .

RUN npm run build

# --- Stage 4: Production (Make Prod) ---
FROM nginx:alpine AS production

COPY --from=builder /app/dist /usr/share/nginx/html

COPY public /usr/share/nginx/html/public

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]