filebeat.inputs:
- type: filestream   
  id: logs
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log

prospector.scanner.fingerprint.enabled: true
prospector.scanner.fingerprint.length: 128

output.logstash:
  hosts: ["logstash:5044"]