filebeat.inputs:
# =========================================
# 1. JSON LOGS (Backend, Chat, Games, Nginx Access)
# =========================================
- type: filestream
  id: json-logs
  enabled: true
  paths:
    - /app/logs/access.log
    - /app/logs/backend.log
    - /app/logs/chat.log
    - /app/logs/games.log
  parsers:
    - ndjson:
        keys_under_root: true
        overwrite_keys: true
  
  prospector.scanner.fingerprint.length: 64

# =========================================
# 2. TEXT LOGS (Frontend, Nginx Error)
# =========================================
- type: filestream
  id: plain-text-logs
  enabled: true
  paths:
    - /app/logs/error.log
    - /app/logs/frontend.log
  
  prospector.scanner.fingerprint.length: 64

output.logstash:
  hosts: ["logstash:5044"]
